version: "3.8"

services:
    web:
        container_name: web
        build: web
        ports:
            - "8004:5000"

    database:
        container_name: database
        restart: always
        image: postgres
        environment:
            - POSTGRES_USER=admin
            - POSTGRES_PASSWORD=mysecretpassword
            - POSTGRES_DB=test
        volumes:
            - db-data:/var/lib/postresql/data

    adminer:
        container_name: adminer
        image: adminer
        restart: always
        ports:
            - "8080:8080"
        depends_on:
            - database

volumes:
    db-data:


